fragment DatasetLineage on Dataset {
  __typename
  ...DatasetLineageBasics
  metadata {
    ...CurrentSourceFetchUrl
    currentPushSources {
      sourceName
    }
    currentLicense {
      ...License
    }
    currentWatermark
    currentUpstreamDependencies {
      ... on DatasetAccessResultNotAccessible {
        id
      }
      ... on DatasetAccessResultAccessible {
        dataset {
          ...DatasetStreamLineageBasics
          metadata {
            ...CurrentSourceFetchUrl
            currentPushSources {
              sourceName
            }
            currentLicense {
              ...License
            }
            currentWatermark
            currentUpstreamDependencies {
              ... on DatasetAccessResultNotAccessible {
                id
              }

              ... on DatasetAccessResultAccessible {
                dataset {
                  ...DatasetStreamLineageBasics
                  metadata {
                    ...CurrentSourceFetchUrl
                    currentPushSources {
                      sourceName
                    }
                    currentLicense {
                      ...License
                    }
                    currentWatermark
                    currentUpstreamDependencies {
                      ... on DatasetAccessResultNotAccessible {
                        id
                      }

                      ... on DatasetAccessResultAccessible {
                        dataset {
                          ...DatasetStreamLineageBasics
                          metadata {
                            ...CurrentSourceFetchUrl
                            currentPushSources {
                              sourceName
                            }
                            currentLicense {
                              ...License
                            }
                            currentWatermark
                            currentUpstreamDependencies {
                              ... on DatasetAccessResultNotAccessible {
                                id
                              }

                              ... on DatasetAccessResultAccessible {
                                dataset {
                                  ...DatasetStreamLineageBasics
                                  metadata {
                                    ...CurrentSourceFetchUrl
                                    currentPushSources {
                                      sourceName
                                    }
                                    currentLicense {
                                      ...License
                                    }
                                    currentWatermark
                                    currentUpstreamDependencies {
                                      ... on DatasetAccessResultNotAccessible {
                                        id
                                      }

                                      ... on DatasetAccessResultAccessible {
                                        dataset {
                                          ...DatasetStreamLineageBasics
                                          metadata {
                                            ...CurrentSourceFetchUrl
                                            currentPushSources {
                                              sourceName
                                            }
                                            currentLicense {
                                              ...License
                                            }
                                            currentWatermark
                                            currentUpstreamDependencies {
                                              ... on DatasetAccessResultNotAccessible {
                                                id
                                              }

                                              ... on DatasetAccessResultAccessible {
                                                dataset {
                                                  ...DatasetStreamLineageBasics
                                                  metadata {
                                                    ...CurrentSourceFetchUrl
                                                    currentPushSources {
                                                      sourceName
                                                    }
                                                    currentLicense {
                                                      ...License
                                                    }
                                                    currentWatermark
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    currentDownstreamDependencies {
      ... on DatasetAccessResultNotAccessible {
        id
      }

      ... on DatasetAccessResultAccessible {
        dataset {
          ...DatasetStreamLineageBasics
          metadata {
            currentPushSources {
              sourceName
            }
            currentDownstreamDependencies {
              ... on DatasetAccessResultNotAccessible {
                id
              }

              ... on DatasetAccessResultAccessible {
                dataset {
                  ...DatasetStreamLineageBasics
                  metadata {
                    currentPushSources {
                      sourceName
                    }
                    currentDownstreamDependencies {
                      ... on DatasetAccessResultNotAccessible {
                        id
                      }

                      ... on DatasetAccessResultAccessible {
                        dataset {
                          ...DatasetStreamLineageBasics
                          metadata {
                            currentPushSources {
                              sourceName
                            }
                            currentDownstreamDependencies {
                              ... on DatasetAccessResultNotAccessible {
                                id
                              }

                              ... on DatasetAccessResultAccessible {
                                dataset {
                                  ...DatasetStreamLineageBasics
                                  metadata {
                                    currentPushSources {
                                      sourceName
                                    }
                                    currentDownstreamDependencies {
                                      ... on DatasetAccessResultNotAccessible {
                                        id
                                      }

                                      ... on DatasetAccessResultAccessible {
                                        dataset {
                                          ...DatasetStreamLineageBasics
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment DatasetLineageBasics on Dataset {
  createdAt
  lastUpdatedAt
  ...DatasetBasics
  data {
    ...DatasetDataSize
  }
  metadata {
    ...CurrentSourceFetchUrl
    currentPushSources {
      sourceName
    }
    currentLicense {
      ...License
    }
    currentWatermark
  }
  owner {
    avatarUrl
  }
}

fragment DatasetStreamLineageBasics on Dataset {
  createdAt
  lastUpdatedAt
  ...DatasetBasics
  data {
    ...DatasetDataSize
  }
  owner {
    avatarUrl
  }
}
