mutation createDatasetAsCollection($datasetAlias: DatasetAlias!, $datasetVisibility: DatasetVisibility!) {
  datasets {
    createCollection(datasetAlias: $datasetAlias, datasetVisibility: $datasetVisibility) {
      ... on CreateDatasetResultSuccess {
        message
        dataset {
          ...DatasetBasics
        }
      }

      ... on CreateDatasetResultInvalidSnapshot {
        message
      }

      ... on CreateDatasetResultMissingInputs {
        message
      }

      ... on CreateDatasetResultNameCollision {
        message
      }

      ... on CreateDatasetResultNameCollision {
        message
      }

      ... on MetadataManifestMalformed {
        message
      }

      ... on MetadataManifestUnsupportedVersion {
        message
      }
    }
  }
}
